# permissions for end users to view cclubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cclub-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd-example
    app.kubernetes.io/part-of: crd-example
    app.kubernetes.io/managed-by: kustomize
  name: cclub-viewer-role
rules:
- apiGroups:
  - cloud.my.domain
  resources:
  - cclubs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.my.domain
  resources:
  - cclubs/status
  verbs:
  - get
