---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloud.my.domain
  resources:
  - cclubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.my.domain
  resources:
  - cclubs/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.my.domain
  resources:
  - cclubs/status
  verbs:
  - get
  - patch
  - update
