apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: cclub-operator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd-example
    app.kubernetes.io/part-of: crd-example
    app.kubernetes.io/managed-by: kustomize
  name: cclub-operator
  namespace: system
