# Defining storageclass manually because: storageclass.storage.k8s.io "cclub-volume" not found

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cclub-volume
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Shared